document.querySelectorAll("#sTimeFrom").item(0).onchange=function(){var indexFrom=document.querySelectorAll("#sTimeFrom").item(0).selectedIndex;var indexBefore=document.querySelectorAll("#sTimeBefore").item(0).selectedIndex;if((indexBefore-indexFrom)<1){document.querySelectorAll("#sTimeBefore").item(0).selectedIndex=indexFrom;}}
document.querySelectorAll("#sTimeBefore").item(0).onchange=function(){var indexFrom=document.querySelectorAll("#sTimeFrom").item(0).selectedIndex;var indexBefore=document.querySelectorAll("#sTimeBefore").item(0).selectedIndex;if((indexBefore-indexFrom)<1){document.querySelectorAll("#sTimeFrom").item(0).selectedIndex=indexBefore;}}
document.addEventListener("DOMContentLoaded",function(){document.querySelectorAll('#cbVisitTime').item(0).checked=false;var d=new Date();var monthA="Января, Февраля, Марта, Апреля, Мая, Июня, Июля, Августа, Сентября, Октября, Ноября, Декабря".split(',');var dayA="Вс, Пн, Вт, Ср, Чт, Пт, Сб".split(",");for(i=0;i<7;i++){var option=document.createElement('option');var text='';var sRed;if(i==0){text='Завтра, ';}
if(d.getDay()>=5){sRed='sRed';}
else{sRed='sGrey'}
d.setDate(d.getDate()+1);option.innerHTML=text+d.getDate()+' '+monthA[d.getMonth()]+' <span class="'+sRed+'">'+dayA[d.getDay()]+'<span>';document.querySelectorAll('#selectDate').item(0).appendChild(option);}});document.addEventListener('DOMContentLoaded',function(){$(".dSummaryWrap input[type=tel] ").mask("+7(999) 999-99-99");var files=document.querySelectorAll('#inputFile').item(0).files;var lbl=document.querySelectorAll(".dSummaryWrap mark").item(0);var wrapper=$(".file_upload"),inp=wrapper.find("input"),btn=wrapper.find("span");btn.focus(function(){inp.focus()});var file_api=(window.File&&window.FileReader&&window.FileList&&window.Blob)?true:false;function renderImage(file){var reader=new FileReader();reader.onload=function(event){theUrl=event.target.result;var img=document.createElement('img');img.src=theUrl;img.alt='';img.className='img';document.querySelectorAll('.dFotoPan').item(0).insertBefore(img,document.querySelectorAll('.dFotoPan').item(0).firstChild);}
reader.readAsDataURL(file);}
inp.change(function(){var file_name='';var filesCount=inp[0].files.length;while(document.querySelectorAll('.img').length>0){document.querySelectorAll('.dFotoPan').item(0).removeChild(document.querySelectorAll('.img').item(0));}
if(file_api&&inp[0].files[0])
for(i=0;i<filesCount;i++){file_name+=inp[0].files[i].name+'; ';renderImage(inp[0].files[i]);}
else
file_name=inp.val().replace("C:\\fakepath\\",'');if(!file_name.length)
return;lbl.innerHTML=(file_name+" ["+filesCount+" шт.]");document.querySelectorAll('.dSummaryWrap textarea').item(0).style.display='block';document.querySelectorAll('.dSummaryWrap input[type=tel]').item(0).style.display='inline-block';document.querySelectorAll('#bDefectsFoto').item(0).style.display='inline-block';}).change();document.querySelectorAll('#inputFile').item(0).onchange=function(){files=this.files;};$('#bDefectsFoto').click(function(event){event.stopPropagation();event.preventDefault();var data=new FormData();var message=document.querySelectorAll('.dSummaryWrap textarea').item(0).value;var tel=document.querySelectorAll('.dSummaryWrap input[type=tel]').item(0).value;data.append('message',message);data.append('tel',tel);if(files.length!=0){$.each(files,function(key,value){data.append(key,value);});$.ajax({url:'../phpfiles/sendPhoto.php?uploadfiles',type:'POST',data:data,cache:false,dataType:'json',processData:false,contentType:false,success:function(respond,textStatus,jqXHR){if(typeof respond.error==='undefined'){$('#answer').html('');document.querySelectorAll('.dSummaryWrap mark').item(0).innerHTML='';document.querySelectorAll('.file_upload input[type=file]').item(0).value='';var loaded=document.createElement('div');loaded.className='loadedDiv';loaded.innerHTML='Фото успешно отправлено!';document.querySelectorAll('.dSummaryWrap > div').item(0).appendChild(loaded);}
else{console.log('ОШИБКИ ОТВЕТА сервера: '+respond.error);}},error:function(jqXHR,textStatus,errorThrown){console.log('ОШИБКИ AJAX запроса: '+textStatus);}})}});});document.addEventListener('DOMContentLoaded',function(){var sp1=Number(document.querySelectorAll('#sp1').item(0).innerHTML);var sp2=Number(document.querySelectorAll('#sp2').item(0).innerHTML);var sp3=Number(document.querySelectorAll('#sp3').item(0).innerHTML);var sp4=Number(document.querySelectorAll('#sp4').item(0).innerHTML);for(i=0;i<4;i++){document.querySelectorAll('.selQuant').item(i).selectedIndex=0;document.querySelectorAll('.selQuant').item(i).onchange=function(){var num=Number(this.id.substr(-1));switch(num){case 1:var value=sp1-50*this.selectedIndex;break;case 2:var value=sp2-50*this.selectedIndex;break;case 3:var value=sp3-50*this.selectedIndex;break;case 4:var value=sp4-100*this.selectedIndex;break;}
document.querySelectorAll('#sp'+this.id.substr(-1)).item(0).innerHTML=value;}}});function startTimer(){var now=new Date().getTime();var time=Number(localStorage.getItem('fvisit'));var deltaTime=parseInt(Number(now-time)/60000);var text='';if(deltaTime<30){var string=parseInt(30*60-deltaTime*60);text='Смазка ВСЕХ окон бесплатно!';}
if(deltaTime>=30){var string=new Date(time);string.setHours(21,00,00,00);string=Date.parse(string);string=parseInt((string-now)/1000);text='Смазка бесплатно!';}
if((string>0)){document.querySelectorAll('.dlOffer').item(0).style.display='block';document.querySelectorAll('.dlOffer mark').item(0).innerHTML=text;$('#sTime').timeTo({seconds:string,fontSize:16,displayDays:0,callback:function(){document.querySelectorAll('.dlOffer').item(0).style.display='none';startTimer();}});}}